language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vincezzh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vincezzh/docker-react npm run test